import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import me from "./my1.jpg";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}> 
        <header className="text-white body-font bg-gradient-to-r from-slate-900 via-slate-800 to-slate-900 border-b border-slate-700/50">
          <div className="container mx-auto flex flex-wrap py-4 px-6 flex-col md:flex-row items-center justify-between">
            <a className="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0 group">
              <div className="avatar">
                <div className="ring-2 ring-slate-400/30 ring-offset-2 ring-offset-slate-900 w-20 rounded-full overflow-hidden transition-all duration-300 group-hover:ring-slate-400/50">
                  <Image src={me} alt="me" className="object-cover" />
                </div>
              </div>
              <h1 className="ml-4 text-3xl font-serif font-bold">
                <span className="bg-clip-text text-transparent bg-gradient-to-r from-white via-slate-200 to-white hover:from-slate-200 hover:to-white transition-all duration-300">
                  PortFolio
                </span>
              </h1>
            </a>
            <nav className="md:ml-auto flex flex-wrap items-center justify-center text-base gap-6 font-sans">
              {["Home", "About", "Skills", "Projects", "Services", "Contact"].map((item) => (
                <Link 
                  key={item} 
                  href={`/${item}`} 
                  className="relative group px-1"
                >
                  <span className="text-slate-200 hover:text-white transition-colors duration-200">
                    {item}
                  </span>
                  <span className="absolute -bottom-0.5 left-0 w-0 h-[2px] bg-slate-400/50 group-hover:w-full transition-all duration-300"></span>
                </Link>
              ))}
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
